/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    java
    `maven-publish`
    kotlin("plugin.serialization") version "1.6.21"
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    implementation("io.vertx:vertx-web-client:4.2.4")
    implementation("io.vertx:vertx-web-validation:4.2.4")
    implementation("io.vertx:vertx-health-check:4.2.4")
    implementation("io.vertx:vertx-web:4.2.4")
    implementation("io.opentelemetry:opentelemetry-bom:1.13.0")
    implementation("io.opentelemetry:opentelemetry-exporter-zipkin:1.13.0")
    implementation("io.opentelemetry:opentelemetry-exporter-jaeger:1.13.0")
    implementation("io.opentelemetry:opentelemetry-semconv:1.11.0-alpha")
    implementation("io.opentelemetry:opentelemetry-sdk:1.13.0")
    implementation("io.opentelemetry:opentelemetry-api:1.13.0")
    implementation("io.vertx:vertx-shell:4.2.4")
    implementation("io.vertx:vertx-web-api-contract:4.2.4")
    implementation("io.vertx:vertx-rx-java3:4.2.4")
    implementation("io.vertx:vertx-dropwizard-metrics:4.2.4")
    implementation("io.vertx:vertx-config:4.2.4")
    implementation("io.vertx:vertx-pg-client:4.2.4")
    implementation("io.vertx:vertx-lang-kotlin-coroutines:4.2.4")
    implementation("io.vertx:vertx-lang-kotlin:4.2.4")
    implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.6.10")
    implementation("org.slf4j:slf4j-api:2.0.0-alpha6")
    implementation("ch.qos.logback:logback-core:1.3.0-alpha13")
    implementation("net.logstash.logback:logstash-logback-encoder:5.2")
    implementation("ch.qos.logback:logback-classic:1.3.0-alpha13")
    implementation("am.ik.yavi:yavi:0.10.0")
    implementation("com.fasterxml.jackson.module:jackson-module-parameter-names:2.13.1")
    implementation("com.fasterxml.jackson.datatype:jackson-datatype-jsr310:2.13.1")
    implementation("com.fasterxml.jackson.datatype:jackson-datatype-jdk8:2.13.1")
    implementation("com.fasterxml.jackson.core:jackson-databind:2.13.1")
    implementation("com.amazonaws:aws-java-sdk:1.12.167")
    implementation("org.jetbrains.kotlinx:kotlinx-serialization-json:1.3.2")
    testImplementation("io.vertx:vertx-junit5:4.2.4")
    testImplementation("org.junit.jupiter:junit-jupiter-api:5.7.0")
    testImplementation("org.junit.jupiter:junit-jupiter-engine:5.7.0")
}

group = "com.shieldtech"
version = "1.0.0-SNAPSHOT"
description = "sales-guide"
java.sourceCompatibility = JavaVersion.VERSION_1_8

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}
