version: "3.7"

services:
  localstack:
    image: localstack/localstack:0.12.15
    ports:
      - "443:443"
      - "53:53"
      - "${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}"
      - "4571:4571"
      - "4566:4566"
      - "4510-4520:4510-4520"
    environment:
      - DEFAULT_REGION=sa-east-1
      - SERVICES=s3,dynamodb,sqs,secretsmanager,s3api,route53,kms,sns,cloudformation,eks,apigateway,lambda,cloudwatch,iam,ses,cognito-idp,cloudtrail,es,firehose,rds,elasticache,ssm
      - DATA_DIR=/tmp/localstack/data
      - HOST_TMP_FOLDER=${TMPDIR}
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DEBUG=1
      - KINESIS_PROVIDER=kinesalite
      - LOCALSTACK_API_KEY=4utlOfXaWg
#      - SMTP_HOST=smtp.gmail.com
#      - SMTP_USER=estudo.async.hb@gmail.com
#      - SMTP_PASS=Hbasync2018
#      - SMTP_EMAIL=estudo.async.hb@gmail.com
      - SMTP_HOST=email-smtp.us-east-2.amazonaws.com
      - SMTP_USER=AKIA4TOL2AU6U4MDC3E3
      - SMTP_PASS=BGnTNSVB0ZXO69LAEYubYjamx05Um+WxtNY2cG6tGGnz
      - SMTP_EMAIL=estudo.async.hb@gmail.com
      - LAMBDA_EXECUTOR=docker-reuse
      - LAMBDA_REMOTE_DOCKER=1
      - DISABLE_CORS_CHECKS=1
      - DISABLE_CUSTOM_CORS_S3=1
      - DISABLE_CUSTOM_CORS_APIGATEWAY=1
      - EXTRA_CORS_ALLOWED_ORIGINS=*
      - EXTRA_CORS_ALLOWED_HEADERS=*
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

  stepfunctions:
    container_name: stepfunctions
    image: amazon/aws-stepfunctions-local:latest
    environment:
      - LAMBDA_ENDPOINT=http://localstack:4566
    ports:
      - '8083:8083'